#!/usr/bin/env python3
"""Write the camera extrinsics the ROS pipeline uses (ros2/src/ppp_bringup/config/calibration.yaml) from the sim's
ground truth in config.yaml `sim:`. A STAND-IN for hand-eye calibration (I-018): a real cell would measure these.

  .venv/bin/python sim/write_calibration.py

  fixed camera: panda_link0 -> camera_color_optical_frame        (eye-to-hand)
  wrist camera: panda_hand  -> wrist_camera_color_optical_frame  (eye-in-hand)
Both frames are OpenCV optical frames (+z forward, +y down), as the cameras publish.
"""
import os
import sys

import numpy as np
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
from vision import load_config  # noqa: E402
from vision import transforms as tf  # noqa: E402

OUT = os.path.join(REPO, 'ros2', 'src', 'ppp_bringup', 'config', 'calibration.yaml')


def entry(parent, child, T):
    return {'parent': parent, 'child': child, 'xyz': [round(float(v), 6) for v in T[:3, 3]],
            'quat_xyzw': [round(float(v), 8) for v in tf.R_to_quat(T[:3, :3])]}


def main():
    cfg = load_config()['sim']
    cam, wrist = cfg['camera'], cfg['wrist_camera']
    T_base_cam = tf.look_at(cam['eye'], cam['target'])    # sim world = robot base (panda_link0)
    T_hand_cam = tf.make_T(tf.rot_z(np.deg2rad(wrist['mount_yaw_deg'])), wrist['mount_xyz'])
    doc = {'source': 'sim ground truth (config.yaml sim:) - STAND-IN for hand-eye calibration, see '
                     'docs/DECISIONS.md I-018',
           'fixed_camera': entry('panda_link0', 'camera_color_optical_frame', T_base_cam),
           'wrist_camera': entry('panda_hand', 'wrist_camera_color_optical_frame', T_hand_cam)}
    with open(OUT, 'w') as f:
        f.write('# Camera extrinsics for the ROS pipeline, published as static TF by ppp_bringup.\n'
                '# Generated by sim/write_calibration.py - do not edit by hand.\n')
        yaml.safe_dump(doc, f, sort_keys=False)
    print('wrote %s' % os.path.relpath(OUT, REPO))


if __name__ == '__main__':
    main()
